### ISSUE TITLE
Summary export permission denied

### ISSUE THREAD

**Issue by edno** [grafana/k6-action#1]
When passing the flag `--summary-export results.json` then an error is raised:
```
level=error msg="failed to create summary export file" error="open results.json: permission denied"
```

The result is that no summary file is created.

Example of step:
```yaml
uses: k6io/action@v0.1
with:
  filename: scenarios/${{ github.event.inputs.scenario }}.js
  flags: --summary-export ${{ github.event.inputs.scenario }}.results.json
```

The expected result is that the flag works like on a local environment, and the `result.json` file is created and can further be exported using `actions/download-artifact@v2`
```yaml
uses: actions/upload-artifact@v2
with:
  name: ${{ github.event.inputs.scenario }}.results.json
  path: ${{ github.event.inputs.scenario }}.results.json
```
