### ISSUE TITLE
how to specify reporter output using this action ?

### ISSUE THREAD

**Issue by PavanMudigondaTR** [grafana/k6-action#10]
Please clarify how to specify html, json reporter output using this action ?

**Comment by ppcano** [comment]
Hey Pavan, 

You can pass the --out CLI option as follow:

```yaml
      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: test.js
          flags: --out json=results.json
```

Check out the following tutorial for the entire instructions and the various alternatives to integrate with GitHub actions: https://k6.io/blog/load-testing-using-github-actions/#using-the-json-output-for-time-series-data
