### ISSUE TITLE
Support  glob patterns to select multiple tests for sequential execution

### ISSUE THREAD

**Issue by ppcano** [grafana/k6-action#19]
For instance: `**/k6-tests/**/*.js`

See examples:

https://github.com/grafana/k6-github-action
https://github.com/grafana/quickpizza/blob/main/.github/workflows/k6-tests.yaml

**Comment by shay-ul** [comment]
+1 , I did some GitHub Action trickery to get such functionality working, but it can be awesome if this can be supported natively.

```
name: Grafana K6
on: workflow_dispatch
jobs:
  list-scripts:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(ls k6/*.js | jq -R -s -c 'split("\n")[:-1]')"
  check:
    needs: list-scripts
    runs-on: ubuntu-latest
    strategy:
        matrix:
            script: ${{ fromJson(needs.list-scripts.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2   
      - uses: grafana/k6-action@v0.3.1
        with:
          filename: ${{ matrix.script }}
          flags: --vus 10 --duration 10s --tag test=${{ matrix.script }}
```
