### ISSUE TITLE
Environment Variables

### ISSUE THREAD

**Issue by andresmafra** [grafana/k6-action#3]
Hi, first of all thanks for the excellent work.

Is it possible to pass out environment variables to this action?

**Comment by edno** [comment]
@andresmafra  - I would say the same way as you do it [locally](https://k6.io/docs/using-k6/options#supply-environment-variables), using the [`flags` action option](https://github.com/grafana/k6-action#flags):

```yaml
steps:
  - name: Run k6 local test
    uses: k6io/action@v0.2.0
    with:
      filename: my-script-file.js
      flags: --env MY_VAR=42
```

**Comment by tyler-mastery** [comment]
@andresmafra you can also just scope it to the github action step
```yaml
steps:
  - name: Run k6 local test
    uses: k6io/action@v0.2.0
    with:
      filename: my-script-file.js
    env:
      MY_VAR: 42
```
