### ISSUE TITLE
New Relic integration

### ISSUE THREAD

**Issue by claudiolcastroTW** [grafana/k6-action#7]
Hello, 

Im running k6 on github actions and I need to integrate the reports with New Relic. There is any way I can do it? 
PS: Im following this doc: https://k6.io/docs/results-visualization/new-relic/

Error: `Couldn't flush a batch" error="write udp 127.0.0.1:38703->127.0.0.1:8125: write: connection refused" output=statsd`

**Comment by dandean** [comment]
The same is true for GitHub Actions when used in conjunction with the [Datadog Agent](https://github.com/DataDog/agent-github-action) action:

```
time="2022-06-02T06:50:10Z" level=debug msg="Error while sending metric http_req_duration" error="write udp 127.0.0.1:44061->127.0.0.1:8125: write: connection refused" output=statsd
```

Here's an example workflow:

```yml
name: Load Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  k6:
    runs-on: ubuntu-latest
    steps:
      - uses: datadog/agent-github-action@v1.3
        with:
          container_name: datadog-agent
          image_name: datadog/agent
          api_key: ${{ secrets.DATADOG_API_KEY }}

      - uses: actions/checkout@v2

      - uses: grafana/k6-action@v0.2.0
        with:
          filename: test.js
          flags: --out statsd --vus 10 --duration 10s --verbose
        env:
          K6_DATADOG_ADDR: datadog-agent:8125
          K6_STATSD_ENABLE_TAGS: true
```
